### ISSUE TITLE
small error when compiling with paltformio

### ISSUE THREAD

**Issue by jascdk** [datacute/DoubleResetDetector#10]
Hi

I get this "error" when compiling with platformio.

Is there a way to fix this?

``.pio/libdeps/d1_mini/DoubleResetDetector_ID1679/src/DoubleResetDetector.cpp: In member function 'void DoubleResetDetector::loop()':
.pio/libdeps/d1_mini/DoubleResetDetector_ID1679/src/DoubleResetDetector.cpp:34:42: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (waitingForDoubleReset && millis() > timeout) stop();``

**Comment by datacute** [comment]
Thanks. Fixed in v1.0.3
