### ISSUE TITLE
Write to user RTC area in example

### ISSUE THREAD

**Issue by ordnungswidrig** [datacute/DoubleResetDetector#2]
According to ESP8266 documentation the first 256 bytes in the RTC are reserved for the system. I suggest to change the example to write to address 64 (the addressing is done in 4byte steps). See [ESP8266 SDK API Guide](https://www.espressif.com/sites/default/files/documentation/2c-esp8266_non_os_sdk_api_reference_en.pdf) page 19.

**Comment by datacute** [comment]
Double Reset Detector calls ESP.rtcUserMemoryWrite which adds 64:
https://github.com/esp8266/Arduino/blob/master/cores/esp8266/Esp.cpp#L131

**Comment by ordnungswidrig** [comment]
Oh, silly me, I was sure I had checked that. Keep up the good work.
