### ISSUE TITLE
Add to the Arduino Library Manager for easier installation

### ISSUE THREAD

**Issue by witnessmenow** [datacute/DoubleResetDetector#3]
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

Basically i think you would need to just a properties file and move the code into a src folder and do a release.

Here is an example properties file
https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot/blob/master/library.properties

I could push a PR with the changes if you want (but I would need a contact email to put in the Maintainer field)

**Comment by datacute** [comment]
Thanks for pointing out how easy it is, I'll get to it.

**Comment by datacute** [comment]
Done

**Comment by witnessmenow** [comment]
Added from the library manager there on my other PC, thanks a lot!
