### ISSUE TITLE
Nodemcu flash button ?

### ISSUE THREAD

**Issue by ErfanDL** [datacute/DoubleResetDetector#5]
Hi. this is nice library but how can I define nodemcu flash button to resetting configuration ?

thanks

**Comment by datacute** [comment]
The nodemcu flash button simply pulls GPIO0 to ground.
The esp8266 can use GPIO0 as a normal input with an internal pull-up.
It is used when Reset is pressed to signal that the esp8266 should be programmed from the UART, apart from that it is a standard button.

The DoubleResetDetector library is designed for boards like the Wemos D1 mini, which only have a single button tied to reset, providing a means of triggering a re-configuration without needing to add a special re-configuration button.

The Nodemcu flash button could be used as a reconfiguration button without this library.
