### ISSUE TITLE
How to prevent Restart on first press?

### ISSUE THREAD

**Issue by obykoo** [datacute/DoubleResetDetector#6]
I would like to use your library to perform "factory reset" so some code needs to be run in order to erase data after double clicking reset button. 
But the problem is, that upon first press device is restarted so actually it never catch double press of reset button. How do I prevent this restart?

**Comment by datacute** [comment]
The library uses EEPROM to store whether it has just been reset, then clears that setting after a while via the call from within the loop(). 
Restarting the device when reset is pressed is expected, when it starts up, it will record in EEPROM that it has just started up, and if you reset it again soon enough after that, when it starts up it will read the EEPROM and see that it has started up twice in quick succession.
You can't use this library to suppress the reset button from resetting the device.
