### ISSUE TITLE
library.properties in version 1.0.0 shows version 0.0.2

### ISSUE THREAD

**Issue by neophiliac** [datacute/DoubleResetDetector#8]
The library.properties file in version 1.0.0 contains this line:

version=0.0.2

**Comment by datacute** [comment]
Thanks for pointing that out, and sorry for any confusion that caused.

**Comment by neophiliac** [comment]
I noticed that I had an out-of-date version, and that after updating I saw the same version. So no harm, just a couple minutes lost. I've done far worse! :)

**Comment by datacute** [comment]
v1.0.1 released. The only change is the version in the library.properties

**Comment by neophiliac** [comment]
I don't see that version on github. I also don't see any updates since July 1, 2017.

**Comment by datacute** [comment]
Thanks @neophiliac - I had forgotten to push the change before creating a new release. v1.0.2 should now fix that.
